#!/bin/bash
# details:
#	https://tomcat.apache.org/maven-plugin-trunk/tomcat7-maven-plugin/usage.html
#	http://tomcat.apache.org/maven-plugin-trunk/tomcat7-maven-plugin/plugin-info.html
cd demo-spring-free
mvn clean tomcat7:run
